### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by sota0121** [sota0121/lab#1]
# samples

- [x] add the existing samples
  - [x] django
  - [x] fastapi
  - [x] k8s official examples
  - [x] python-grpc-demo
  - [x] dockerfile-sample
  - [x] go-sample
  - [x] minimum-redis
- [ ] redis pub/sub in python
- [ ] redis kvs in python
- [ ] time calling api server in golang
- [ ] ...

# playground

- [ ] create python dev env with docker
- [ ] create go dev env with docker
- [ ] ...

# snippet

- [ ] python import sample consists of some packages / modules
- [ ] make your own python packages
- [ ] make your own go module
- [ ] ...
